# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Bat\CSSF\CSSF_UI.ui'
#
# Created: Sun Jan 03 22:04:11 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(676, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1024, 400))
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/main_ico/LRF3023.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        self.widget = QtGui.QWidget(MainWindow)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.layoutWidget = QtGui.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 131, 30))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_PortNO = QtGui.QLabel(self.layoutWidget)
        self.label_PortNO.setObjectName(_fromUtf8("label_PortNO"))
        self.horizontalLayout.addWidget(self.label_PortNO)
        self.comboBox_PortNO = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_PortNO.sizePolicy().hasHeightForWidth())
        self.comboBox_PortNO.setSizePolicy(sizePolicy)
        self.comboBox_PortNO.setObjectName(_fromUtf8("comboBox_PortNO"))
        self.horizontalLayout.addWidget(self.comboBox_PortNO)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(200, 20, 20, 351))
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 171, 261))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 160, 88, 91))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Position_bt = QtGui.QPushButton(self.layoutWidget1)
        self.Position_bt.setObjectName(_fromUtf8("Position_bt"))
        self.verticalLayout_2.addWidget(self.Position_bt)
        self.Search_bt = QtGui.QPushButton(self.layoutWidget1)
        self.Search_bt.setCheckable(False)
        self.Search_bt.setChecked(False)
        self.Search_bt.setObjectName(_fromUtf8("Search_bt"))
        self.verticalLayout_2.addWidget(self.Search_bt)
        self.Bias_bt = QtGui.QPushButton(self.layoutWidget1)
        self.Bias_bt.setObjectName(_fromUtf8("Bias_bt"))
        self.verticalLayout_2.addWidget(self.Bias_bt)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 151, 108))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_azimuth_angle = QtGui.QLabel(self.layoutWidget2)
        self.label_azimuth_angle.setObjectName(_fromUtf8("label_azimuth_angle"))
        self.horizontalLayout_2.addWidget(self.label_azimuth_angle)
        self.lineEdit_azimuth_angle = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_azimuth_angle.setObjectName(_fromUtf8("lineEdit_azimuth_angle"))
        self.horizontalLayout_2.addWidget(self.lineEdit_azimuth_angle)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_pitch_angle = QtGui.QLabel(self.layoutWidget2)
        self.label_pitch_angle.setObjectName(_fromUtf8("label_pitch_angle"))
        self.horizontalLayout_3.addWidget(self.label_pitch_angle)
        self.lineEdit_pitch_angle = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_pitch_angle.setObjectName(_fromUtf8("lineEdit_pitch_angle"))
        self.horizontalLayout_3.addWidget(self.lineEdit_pitch_angle)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_azimuth_velocity = QtGui.QLabel(self.layoutWidget2)
        self.label_azimuth_velocity.setObjectName(_fromUtf8("label_azimuth_velocity"))
        self.horizontalLayout_5.addWidget(self.label_azimuth_velocity)
        self.lineEdit_azimuth_velocity = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_azimuth_velocity.setObjectName(_fromUtf8("lineEdit_azimuth_velocity"))
        self.horizontalLayout_5.addWidget(self.lineEdit_azimuth_velocity)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_pitch_velocity = QtGui.QLabel(self.layoutWidget2)
        self.label_pitch_velocity.setObjectName(_fromUtf8("label_pitch_velocity"))
        self.horizontalLayout_4.addWidget(self.label_pitch_velocity)
        self.lineEdit_pitch_velocity = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_pitch_velocity.setObjectName(_fromUtf8("lineEdit_pitch_velocity"))
        self.horizontalLayout_4.addWidget(self.lineEdit_pitch_velocity)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.groupBox_show = QtGui.QGroupBox(self.widget)
        self.groupBox_show.setGeometry(QtCore.QRect(240, 20, 231, 101))
        self.groupBox_show.setObjectName(_fromUtf8("groupBox_show"))
        self.label_azimuth_angle_show = QtGui.QLabel(self.groupBox_show)
        self.label_azimuth_angle_show.setGeometry(QtCore.QRect(11, 21, 78, 16))
        self.label_azimuth_angle_show.setObjectName(_fromUtf8("label_azimuth_angle_show"))
        self.label_pitch_angle_show = QtGui.QLabel(self.groupBox_show)
        self.label_pitch_angle_show.setGeometry(QtCore.QRect(11, 39, 78, 16))
        self.label_pitch_angle_show.setObjectName(_fromUtf8("label_pitch_angle_show"))
        self.label_azimuth_velocity_show = QtGui.QLabel(self.groupBox_show)
        self.label_azimuth_velocity_show.setGeometry(QtCore.QRect(11, 57, 78, 16))
        self.label_azimuth_velocity_show.setObjectName(_fromUtf8("label_azimuth_velocity_show"))
        self.label_pitch_velocity_show = QtGui.QLabel(self.groupBox_show)
        self.label_pitch_velocity_show.setGeometry(QtCore.QRect(11, 75, 81, 16))
        self.label_pitch_velocity_show.setObjectName(_fromUtf8("label_pitch_velocity_show"))
        self.help_bt = QtGui.QPushButton(self.widget)
        self.help_bt.setGeometry(QtCore.QRect(590, 0, 41, 21))
        self.help_bt.setStyleSheet(_fromUtf8(""))
        self.help_bt.setCheckable(False)
        self.help_bt.setObjectName(_fromUtf8("help_bt"))
        self.line = QtGui.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(30, 40, 100, 0))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.graphicsView_axis = QtGui.QGraphicsView(self.widget)
        self.graphicsView_axis.setGeometry(QtCore.QRect(250, 150, 200, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_axis.sizePolicy().hasHeightForWidth())
        self.graphicsView_axis.setSizePolicy(sizePolicy)
        self.graphicsView_axis.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView_axis.setMouseTracking(True)
        self.graphicsView_axis.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphicsView_axis.setLineWidth(2)
        self.graphicsView_axis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_axis.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_axis.setInteractive(True)
        self.graphicsView_axis.setObjectName(_fromUtf8("graphicsView_axis"))
        MainWindow.setCentralWidget(self.widget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "伺服性能测试设备", None))
        self.label_PortNO.setText(_translate("MainWindow", "串口号:", None))
        self.groupBox.setTitle(_translate("MainWindow", "带参控制指令", None))
        self.Position_bt.setText(_translate("MainWindow", "定位定位", None))
        self.Search_bt.setText(_translate("MainWindow", "搜索控制", None))
        self.Bias_bt.setText(_translate("MainWindow", "偏差控制", None))
        self.label_azimuth_angle.setText(_translate("MainWindow", "方位角度(  °):", None))
        self.lineEdit_azimuth_angle.setText(_translate("MainWindow", "0", None))
        self.label_pitch_angle.setText(_translate("MainWindow", "俯仰角度(  °):", None))
        self.lineEdit_pitch_angle.setText(_translate("MainWindow", "0", None))
        self.label_azimuth_velocity.setText(_translate("MainWindow", "方位速度(°/s):", None))
        self.lineEdit_azimuth_velocity.setText(_translate("MainWindow", "0.01", None))
        self.label_pitch_velocity.setText(_translate("MainWindow", "俯仰速度(°/s):", None))
        self.lineEdit_pitch_velocity.setText(_translate("MainWindow", "0.01", None))
        self.groupBox_show.setTitle(_translate("MainWindow", "测量数据", None))
        self.label_azimuth_angle_show.setText(_translate("MainWindow", "方位角度", None))
        self.label_pitch_angle_show.setText(_translate("MainWindow", "俯仰角度", None))
        self.label_azimuth_velocity_show.setText(_translate("MainWindow", "方位速度", None))
        self.label_pitch_velocity_show.setText(_translate("MainWindow", "俯仰速度", None))
        self.help_bt.setText(_translate("MainWindow", "帮助", None))

import resource_rc
